name: Build

on:
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - uses: actions/setup-python@v3

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.14.1

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libproj-dev proj-bin libeccodes-dev
          sudo apt-get install libgeos-dev

      - name: Build wheels
        env:
          CIBW_BUILD: "cp311-manylinux_x86_64"
          CIBW_BEFORE_BUILD: "pip install setuptools cython numpy wheel"
        run: python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl